-- P2-14 -- ADR-069. `invitation_settings.section_memory`.
--
-- The couple's on/off choice for each section the invitation's CURRENT template does not
-- define, as `{ "section_key": true | false }`. A template change removes such sections from
-- `enabled_sections`; before this column nothing remembered them, so switching back applied the
-- template's defaults instead of the couple's choices. `docs/API/04` promises that switching
-- back restores the display.
--
-- Expand-only (migrations/README.md): a new column with a default, read and written by the
-- change-template service. Existing rows get `{}`, which reproduces the previous behaviour for
-- them until their next template change.
--
-- Generated by `drizzle-kit generate`, then cut down to this statement: the generated diff also
-- re-emitted 0005 and 0006, whose snapshots had been copied from 0004 and never described them.
-- The snapshot chain was repaired in the same change (see the P2-14 record).

ALTER TABLE "invitation_settings" ADD COLUMN "section_memory" jsonb DEFAULT '{}'::jsonb NOT NULL;
